/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as PublicStatusRouteImport } from './routes/public/status/route'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login/route'
import { Route as AdminUsersRouteImport } from './routes/admin/users/route'
import { Route as AdminRolesRouteImport } from './routes/admin/roles/route'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects/route'

// Create Virtual Routes

const AuthIndexLazyImport = createFileRoute('/auth/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const AdminTiposInformeLazyImport = createFileRoute('/admin/tipos-informe')()
const PublicStatusIndexLazyImport = createFileRoute('/public/status/')()
const AuthResetPasswordIndexLazyImport = createFileRoute(
  '/auth/reset-password/',
)()
const AuthLoginIndexLazyImport = createFileRoute('/auth/login/')()
const AdminUsersIndexLazyImport = createFileRoute('/admin/users/')()
const AdminRolesIndexLazyImport = createFileRoute('/admin/roles/')()
const AdminProjectsIndexLazyImport = createFileRoute('/admin/projects/')()
const PublicInformesSlugLazyImport = createFileRoute('/public/informes/$slug')()

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/route.lazy').then((d) => d.Route))

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/route.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const AdminTiposInformeLazyRoute = AdminTiposInformeLazyImport.update({
  id: '/tipos-informe',
  path: '/tipos-informe',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/tipos-informe.lazy').then((d) => d.Route),
)

const PublicStatusRouteRoute = PublicStatusRouteImport.update({
  id: '/public/status',
  path: '/public/status',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRouteRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/auth/reset-password/route.lazy').then((d) => d.Route),
)

const AuthLoginRouteRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/auth/login/route.lazy').then((d) => d.Route),
)

const AdminUsersRouteRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/users/route.lazy').then((d) => d.Route),
)

const AdminRolesRouteRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/roles/route.lazy').then((d) => d.Route),
)

const AdminProjectsRouteRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/projects/route.lazy').then((d) => d.Route),
)

const PublicStatusIndexLazyRoute = PublicStatusIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicStatusRouteRoute,
} as any).lazy(() =>
  import('./routes/public/status/index.lazy').then((d) => d.Route),
)

const AuthResetPasswordIndexLazyRoute = AuthResetPasswordIndexLazyImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthResetPasswordRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/auth/reset-password/index.lazy').then((d) => d.Route),
)

const AuthLoginIndexLazyRoute = AuthLoginIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLoginRouteRoute,
} as any).lazy(() =>
  import('./routes/auth/login/index.lazy').then((d) => d.Route),
)

const AdminUsersIndexLazyRoute = AdminUsersIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/users/index.lazy').then((d) => d.Route),
)

const AdminRolesIndexLazyRoute = AdminRolesIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRolesRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/roles/index.lazy').then((d) => d.Route),
)

const AdminProjectsIndexLazyRoute = AdminProjectsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/projects/index.lazy').then((d) => d.Route),
)

const PublicInformesSlugLazyRoute = PublicInformesSlugLazyImport.update({
  id: '/public/informes/$slug',
  path: '/public/informes/$slug',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/public/informes/$slug.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/public/status': {
      id: '/public/status'
      path: '/public/status'
      fullPath: '/public/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/tipos-informe': {
      id: '/admin/tipos-informe'
      path: '/tipos-informe'
      fullPath: '/admin/tipos-informe'
      preLoaderRoute: typeof AdminTiposInformeLazyImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/public/informes/$slug': {
      id: '/public/informes/$slug'
      path: '/public/informes/$slug'
      fullPath: '/public/informes/$slug'
      preLoaderRoute: typeof PublicInformesSlugLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexLazyImport
      parentRoute: typeof AdminProjectsRouteImport
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminRolesIndexLazyImport
      parentRoute: typeof AdminRolesRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexLazyImport
      parentRoute: typeof AdminUsersRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexLazyImport
      parentRoute: typeof AuthLoginRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexLazyImport
      parentRoute: typeof AuthResetPasswordRouteImport
    }
    '/public/status/': {
      id: '/public/status/'
      path: '/'
      fullPath: '/public/status/'
      preLoaderRoute: typeof PublicStatusIndexLazyImport
      parentRoute: typeof PublicStatusRouteImport
    }
  }
}

// Create and export the route tree

interface AdminProjectsRouteRouteChildren {
  AdminProjectsIndexLazyRoute: typeof AdminProjectsIndexLazyRoute
}

const AdminProjectsRouteRouteChildren: AdminProjectsRouteRouteChildren = {
  AdminProjectsIndexLazyRoute: AdminProjectsIndexLazyRoute,
}

const AdminProjectsRouteRouteWithChildren =
  AdminProjectsRouteRoute._addFileChildren(AdminProjectsRouteRouteChildren)

interface AdminRolesRouteRouteChildren {
  AdminRolesIndexLazyRoute: typeof AdminRolesIndexLazyRoute
}

const AdminRolesRouteRouteChildren: AdminRolesRouteRouteChildren = {
  AdminRolesIndexLazyRoute: AdminRolesIndexLazyRoute,
}

const AdminRolesRouteRouteWithChildren = AdminRolesRouteRoute._addFileChildren(
  AdminRolesRouteRouteChildren,
)

interface AdminUsersRouteRouteChildren {
  AdminUsersIndexLazyRoute: typeof AdminUsersIndexLazyRoute
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersIndexLazyRoute: AdminUsersIndexLazyRoute,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProjectsRouteRoute: typeof AdminProjectsRouteRouteWithChildren
  AdminRolesRouteRoute: typeof AdminRolesRouteRouteWithChildren
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  AdminTiposInformeLazyRoute: typeof AdminTiposInformeLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProjectsRouteRoute: AdminProjectsRouteRouteWithChildren,
  AdminRolesRouteRoute: AdminRolesRouteRouteWithChildren,
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  AdminTiposInformeLazyRoute: AdminTiposInformeLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthLoginRouteRouteChildren {
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
}

const AuthLoginRouteRouteChildren: AuthLoginRouteRouteChildren = {
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
}

const AuthLoginRouteRouteWithChildren = AuthLoginRouteRoute._addFileChildren(
  AuthLoginRouteRouteChildren,
)

interface AuthResetPasswordRouteRouteChildren {
  AuthResetPasswordIndexLazyRoute: typeof AuthResetPasswordIndexLazyRoute
}

const AuthResetPasswordRouteRouteChildren: AuthResetPasswordRouteRouteChildren =
  {
    AuthResetPasswordIndexLazyRoute: AuthResetPasswordIndexLazyRoute,
  }

const AuthResetPasswordRouteRouteWithChildren =
  AuthResetPasswordRouteRoute._addFileChildren(
    AuthResetPasswordRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRouteWithChildren
  AuthResetPasswordRouteRoute: typeof AuthResetPasswordRouteRouteWithChildren
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRouteWithChildren,
  AuthResetPasswordRouteRoute: AuthResetPasswordRouteRouteWithChildren,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicStatusRouteRouteChildren {
  PublicStatusIndexLazyRoute: typeof PublicStatusIndexLazyRoute
}

const PublicStatusRouteRouteChildren: PublicStatusRouteRouteChildren = {
  PublicStatusIndexLazyRoute: PublicStatusIndexLazyRoute,
}

const PublicStatusRouteRouteWithChildren =
  PublicStatusRouteRoute._addFileChildren(PublicStatusRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteRouteWithChildren
  '/admin/roles': typeof AdminRolesRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteRouteWithChildren
  '/public/status': typeof PublicStatusRouteRouteWithChildren
  '/admin/tipos-informe': typeof AdminTiposInformeLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/public/informes/$slug': typeof PublicInformesSlugLazyRoute
  '/admin/projects/': typeof AdminProjectsIndexLazyRoute
  '/admin/roles/': typeof AdminRolesIndexLazyRoute
  '/admin/users/': typeof AdminUsersIndexLazyRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexLazyRoute
  '/public/status/': typeof PublicStatusIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/tipos-informe': typeof AdminTiposInformeLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/auth': typeof AuthIndexLazyRoute
  '/public/informes/$slug': typeof PublicInformesSlugLazyRoute
  '/admin/projects': typeof AdminProjectsIndexLazyRoute
  '/admin/roles': typeof AdminRolesIndexLazyRoute
  '/admin/users': typeof AdminUsersIndexLazyRoute
  '/auth/login': typeof AuthLoginIndexLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexLazyRoute
  '/public/status': typeof PublicStatusIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteRouteWithChildren
  '/admin/roles': typeof AdminRolesRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteRouteWithChildren
  '/public/status': typeof PublicStatusRouteRouteWithChildren
  '/admin/tipos-informe': typeof AdminTiposInformeLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/public/informes/$slug': typeof PublicInformesSlugLazyRoute
  '/admin/projects/': typeof AdminProjectsIndexLazyRoute
  '/admin/roles/': typeof AdminRolesIndexLazyRoute
  '/admin/users/': typeof AdminUsersIndexLazyRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexLazyRoute
  '/public/status/': typeof PublicStatusIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/users'
    | '/auth/login'
    | '/auth/reset-password'
    | '/public/status'
    | '/admin/tipos-informe'
    | '/admin/'
    | '/auth/'
    | '/public/informes/$slug'
    | '/admin/projects/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/public/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/tipos-informe'
    | '/admin'
    | '/auth'
    | '/public/informes/$slug'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/users'
    | '/auth/login'
    | '/auth/reset-password'
    | '/public/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/users'
    | '/auth/login'
    | '/auth/reset-password'
    | '/public/status'
    | '/admin/tipos-informe'
    | '/admin/'
    | '/auth/'
    | '/public/informes/$slug'
    | '/admin/projects/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/public/status/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicStatusRouteRoute: typeof PublicStatusRouteRouteWithChildren
  PublicInformesSlugLazyRoute: typeof PublicInformesSlugLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicStatusRouteRoute: PublicStatusRouteRouteWithChildren,
  PublicInformesSlugLazyRoute: PublicInformesSlugLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/auth",
        "/public/status",
        "/public/informes/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/projects",
        "/admin/roles",
        "/admin/users",
        "/admin/tipos-informe",
        "/admin/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/reset-password",
        "/auth/"
      ]
    },
    "/admin/projects": {
      "filePath": "admin/projects/route.ts",
      "parent": "/admin",
      "children": [
        "/admin/projects/"
      ]
    },
    "/admin/roles": {
      "filePath": "admin/roles/route.ts",
      "parent": "/admin",
      "children": [
        "/admin/roles/"
      ]
    },
    "/admin/users": {
      "filePath": "admin/users/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/users/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login/route.tsx",
      "parent": "/auth",
      "children": [
        "/auth/login/"
      ]
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password/route.tsx",
      "parent": "/auth",
      "children": [
        "/auth/reset-password/"
      ]
    },
    "/public/status": {
      "filePath": "public/status/route.ts",
      "children": [
        "/public/status/"
      ]
    },
    "/admin/tipos-informe": {
      "filePath": "admin/tipos-informe.lazy.tsx",
      "parent": "/admin"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx",
      "parent": "/admin"
    },
    "/auth/": {
      "filePath": "auth/index.lazy.tsx",
      "parent": "/auth"
    },
    "/public/informes/$slug": {
      "filePath": "public/informes/$slug.lazy.tsx"
    },
    "/admin/projects/": {
      "filePath": "admin/projects/index.lazy.tsx",
      "parent": "/admin/projects"
    },
    "/admin/roles/": {
      "filePath": "admin/roles/index.lazy.tsx",
      "parent": "/admin/roles"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.lazy.tsx",
      "parent": "/admin/users"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.lazy.tsx",
      "parent": "/auth/login"
    },
    "/auth/reset-password/": {
      "filePath": "auth/reset-password/index.lazy.tsx",
      "parent": "/auth/reset-password"
    },
    "/public/status/": {
      "filePath": "public/status/index.lazy.tsx",
      "parent": "/public/status"
    }
  }
}
ROUTE_MANIFEST_END */
